name: Java Workflow

on:
  push:
    branches: [ main, workflowAction ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Construir test con Maven
        run: mvn -B clean verify

      - name: Generar Documentacion Java
        run: mvn javadoc:javadoc

      - name: Empaquetar JAR
        run: mvn package

      - name: Subida de Artefactos
        uses: actions/upload-artifact@v4
        with:
          name: Construir-Artefactos
          path: |
            target/*.jar
            target/site/apidocs/
